// Copyright (c) 2023-2025 RapidaAI
// Author: Prashant Srivastav <prashant@rapida.ai>
//
// Licensed under GPL-2.0 with Rapida Additional Terms.
// See LICENSE.md or contact sales@rapida.ai for commercial usage.
package internal_normalizers

import (
	"strings"

	"github.com/rapidaai/pkg/commons"
)

type symbolNormalizer struct {
	logger    commons.Logger
	symbolMap map[string]string
}

func NewSymbolNormalizer(logger commons.Logger) Normalizer {
	return &symbolNormalizer{
		logger:    logger,
		symbolMap: createSymbolMap(),
	}
}

func (sn *symbolNormalizer) Normalize(s string) string {
	for symbol, word := range sn.symbolMap {
		s = strings.ReplaceAll(s, symbol, word)
	}
	return s
}

func createSymbolMap() map[string]string {
	return map[string]string{
		"%": " percent",
		"&": " and",
		"+": " plus",
		"=": " equals",
		"@": " at",
		"#": " hash",
		"⅔": "two-thirds",
		"½": "one-half",
		"¼": "one-quarter",
		"¾": "three-quarters",
		"⅓": "one-third",
		"⅕": "one-fifth",
		"⅖": "two-fifths",
		"⅗": "three-fifths",
		"⅘": "four-fifths",
		"⅙": "one-sixth",
		"⅚": "five-sixths",
		"⅛": "one-eighth",
		"⅜": "three-eighths",
		"⅝": "five-eighths",
		"⅞": "seven-eighths",
		"℃": " degrees celsius",
		"℉": " degrees fahrenheit",
		"£": " pounds",
		"€": " euros",
		"¥": " yen",
		"₩": " won",
		"₿": " bitcoin",
		"™": " trademark",
		"©": " copyright",
		"®": " registered",
		"°": " degrees",
		"±": " plus or minus",
		"×": " multiplied by",
		"÷": " divided by",
		"≈": " approximately",
		"≠": " not equal to",
		"≤": " less than or equal to",
		"≥": " greater than or equal to",
		"∞": " infinity",
		"π": " pi",
		"√": " square root",
		"∑": " sum",
		"∫": " integral",
		"∂": " partial derivative",
		"∆": " delta",
		"∏": " product",
		"∈": " element of",
		"∉": " not an element of",
		"∩": " intersection",
		"∪": " union",
		"∅": " empty set",
		"∀": " for all",
		"∃": " there exists",
		"∄": " there does not exist",
		"∇": " nabla",
		"∋": " contains as member",
		"∌": " does not contain as member",
		"−": " minus",
		"∕": " division slash",
		"∖": " set minus",
		"∗": " asterisk operator",
		"∘": " ring operator",
		"∙": " bullet operator",
		"∛": " cube root",
		"∜": " fourth root",
		"∝": " proportional to",
		"∟": " right angle",
		"∠": " angle",
		"∥": " parallel to",
		"∦": " not parallel to",
		"∧": " logical and",
		"∨": " logical or",
		"∴": " therefore",
		"∵": " because",
		"∶": " ratio",
		"∷": " proportion",
		"∼": " tilde operator",
		"∽": " reversed tilde",
		"≀": " wreath product",
		"≁": " not tilde",
		"≂": " minus tilde",
		"≃": " asymptotically equal to",
		"≄": " not asymptotically equal to",
		"≅": " approximately equal to",
		"≆": " approximately but not actually equal to",
		"≇": " neither approximately nor actually equal to",
		"≉": " not almost equal to",
		"≊": " almost equal or equal to",
		"≋": " triple tilde",
		"≌": " all equal to",
		"≍": " equivalent to",
		"≎": " geometrically equivalent to",
		"≏": " difference between",
		"≐": " approaches the limit",
		"≑": " geometrically equal to",
		"≒": " approximately equal to or the image of",
		"≓": " image of or approximately equal to",
		"≔": " colon equals",
		"≕": " equals colon",
		"≖": " ring in equal to",
		"≗": " ring equal to",
		"≘": " corresponds to",
		"≙": " estimates",
		"≚": " equiangular to",
		"≛": " star equals",
		"≜": " delta equal to",
		"≝": " equal to by definition",
		"≞": " measured by",
		"≟": " questioned equal to",
		"≡": " identical to",
		"≢": " not identical to",
		"≣": " strictly equivalent to",
		"≦": " less-than over equal to",
		"≧": " greater-than over equal to",
		"≨": " less-than but not equal to",
		"≩": " greater-than but not equal to",
		"≪": " much less-than",
		"≫": " much greater-than",
		"≬": " between",
		"≭": " not equivalent to",
		"≮": " not less-than",
		"≯": " not greater-than",
		"≰": " neither less-than nor equal to",
		"≱": " neither greater-than nor equal to",
		"≲": " less-than or equivalent to",
		"≳": " greater-than or equivalent to",
		"≴": " neither less-than nor equivalent to",
		"≵": " neither greater-than nor equivalent to",
		"≶": " less-than or greater-than",
		"≷": " greater-than or less-than",
		"≸": " neither less-than nor greater-than",
		"≹": " neither greater-than nor less-than",
		"≺": " precedes",
		"≻": " succeeds",
		"≼": " precedes or equal to",
		"≽": " succeeds or equal to",
		"≾": " precedes or equivalent to",
		"≿": " succeeds or equivalent to",
		"⊀": " does not precede",
		"⊁": " does not succeed",
		"⊂": " subset of",
		"⊃": " superset of",
		"⊄": " not a subset of",
		"⊅": " not a superset of",
		"⊆": " subset of or equal to",
		"⊇": " superset of or equal to",
		"⊈": " neither a subset of nor equal to",
		"⊉": " neither a superset of nor equal to",
		"⊊": " subset of with not equal to",
		"⊋": " superset of with not equal to",
		"⊌": " multiset",
		"⊍": " multiset multiplication",
		"⊎": " multiset union",
		"⊏": " square image of",
		"⊐": " square original of",
		"⊑": " square image of or equal to",
		"⊒": " square original of or equal to",
		"⊓": " square cap",
		"⊔": " square cup",
		"⊕": " circled plus",
		"⊖": " circled minus",
		"⊗": " circled times",
		"⊘": " circled division slash",
		"⊙": " circled dot operator",
		"⊚": " circled ring operator",
		"⊛": " circled asterisk operator",
		"⊜": " circled equals",
		"⊝": " circled dash",
		"⊞": " squared plus",
		"⊟": " squared minus",
		"⊠": " squared times",
		"⊡": " squared dot operator",
		"⊢": " right tack",
		"⊣": " left tack",
		"⊤": " down tack",
		"⊥": " up tack",
		"⊦": " assertion",
		"⊧": " models",
		"⊨": " true",
		"⊩": " forces",
		"⊪": " triple vertical bar right turnstile",
		"⊫": " double vertical bar double right turnstile",
		"⊬": " does not prove",
		"⊭": " not true",
		"⊮": " does not force",
		"⊯": " negated double vertical bar double right turnstile",
		"⊰": " precedes under relation",
		"⊱": " succeeds under relation",
		"⊲": " normal subgroup of",
		"⊳": " contains as normal subgroup",
		"⊴": " normal subgroup of or equal to",
		"⊵": " contains as normal subgroup or equal to",
		"⊶": " original of",
		"⊷": " image of",
		"⊸": " multimap",
		"⊹": " hermitian conjugate matrix",
		"⊺": " intercalate",
		"⊻": " xor",
		"⊼": " nand",
		"⊽": " nor",
		"⊾": " right angle with arc",
		"⊿": " right triangle",
		"⋀": " n-ary logical and",
		"⋁": " n-ary logical or",
		"⋂": " n-ary intersection",
		"⋃": " n-ary union",
		"⋄": " diamond operator",
		"⋅": " dot operator",
		"⋆": " star operator",
		"⋇": " division times",
		"⋈": " bowtie",
		"⋉": " left normal factor semidirect product",
		"⋊": " right normal factor semidirect product",
		"⋋": " left semidirect product",
		"⋌": " right semidirect product",
		"⋍": " reversed tilde equals",
		"⋎": " curly logical or",
		"⋏": " curly logical and",
		"⋐": " double subset",
		"⋑": " double superset",
		"⋒": " double intersection",
		"⋓": " double union",
		"⋔": " pitchfork",
		"⋕": " equal and parallel to",
		"⋖": " less-than with dot",
		"⋗": " greater-than with dot",
		"⋘": " very much less-than",
		"⋙": " very much greater-than",
		"⋚": " less-than equal to or greater-than",
		"⋛": " greater-than equal to or less-than",
		"⋜": " equal to or less-than",
		"⋝": " equal to or greater-than",
		"⋞": " equal to or precedes",
		"⋟": " equal to or succeeds",
		"⋠": " does not precede or equal",
		"⋡": " does not succeed or equal",
		"⋢": " not square image of or equal to",
		"⋣": " not square original of or equal to",
		"⋤": " square image of or not equal to",
		"⋥": " square original of or not equal to",
		"⋦": " less-than but not equivalent to",
		"⋧": " greater-than but not equivalent to",
		"⋨": " precedes but not equivalent to",
		"⋩": " succeeds but not equivalent to",
		"⋪": " not normal subgroup of",
		"⋫": " does not contain as normal subgroup",
		"⋬": " not normal subgroup of or equal to",
		"⋭": " does not contain as normal subgroup or equal",
		"⋮": " vertical ellipsis",
		"⋯": " midline horizontal ellipsis",
		"⋰": " up right diagonal ellipsis",
		"⋱": " down right diagonal ellipsis",
		"⋲": " element of with long horizontal stroke",
		"⋳": " element of with vertical bar at end of horizontal stroke",
		"⋴": " small element of with vertical bar at end of horizontal stroke",
		"⋵": " element of with dot above",
		"⋶": " element of with overbar",
		"⋷": " small element of with overbar",
		"⋸": " element of with underbar",
		"⋹": " element of with two horizontal strokes",
		"⋺": " contains with long horizontal stroke",
		"⋻": " contains with vertical bar at end of horizontal stroke",
		"⋼": " small contains with vertical bar at end of horizontal stroke",
		"⋽": " contains with overbar",
		"⋾": " small contains with overbar",
		"⋿": " z notation bag membership",
	}
}
