version: 0.2
env:
  parameter-store:
    DEPLOY_KEY: "DEPLOY_KEY"
  variables:
    GO_PROJECT_MODULE: "github.com/rapidaai/protos"
    OUT_DIR: "/protos/"
phases:
  install:
    commands:
      - echo "add deploy key"
      - mkdir -p ~/.ssh
      - echo "$DEPLOY_KEY" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - eval "$(ssh-agent -s)"
      - echo "disable strict host key check"
      - touch ~/.ssh/config
      - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    runtime-versions:
      golang: 1.21
  pre_build:
    commands:
      - export PB_REL=https://github.com/protocolbuffers/protobuf/releases
      - curl -LO $PB_REL/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip
      - unzip protoc-3.20.0-linux-x86_64.zip -d $HOME/protobuf
      - ln -s $HOME/protobuf/bin/protoc /usr/local/bin/protoc
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.0
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

  build:
    commands:
      - git submodule update --init --recursive
      - echo "updating submodule"
      - go mod download
      - sh bin/artifacts-generate.sh
      - GOOS=linux GOARCH=amd64 go build -o web-api.0.0.1 cmd/web.go
      - cp codedeploy/env.production ./env
artifacts:
  files:
    - web-api.0.0.1
    - appspec.yml
    - env
    - codedeploy/*
cache:
  paths:
    - "/go/pkg/**/*"
    - "/go/pkg/**.*"
