version: 0.2
env:
  variables:
    GO_PROJECT_MODULE: "github.com/lexatic/web-backend/protos/lexatic-backend"
    OUT_DIR: "/protos/lexatic-backend/"
phases:
  install:
    commands:
      - echo "add deploy key"
      - eval "$(ssh-agent -s)"
      - ssh-add <(echo "$DEPLOY_KEY" | base64 -d)
      - echo "disable strict host key check"
      - mkdir -p ~/.ssh
      - touch ~/.ssh/config
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - git submodule update --init --recursive
      - echo "updateing submodule"
    runtime-versions:
      golang: 1.20
  pre_build:
    commands:
      - export PB_REL=https://github.com/protocolbuffers/protobuf/releases
      - curl -LO $PB_REL/download/v3.20.0/protoc-3.20.0-linux-x86_64.zip
      - unzip protoc-3.20.0-linux-x86_64.zip -d $HOME/protobuf
      - ln -s $HOME/protobuf/bin/protoc /usr/local/bin/protoc
      - go get -u github.com/golang/protobuf/proto
      - go get -u github.com/golang/protobuf/protoc-gen-go
      - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
      - go install google.golang.org/protobuf/cmd/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc

  build:
    commands:
      - go mod download
      - sh scripts/grpc-server.sh
      - GOOS=linux GOARCH=amd64 go build -o web-api.0.0.1 api/main.go
      - cp codedeploy/env.production ./env
artifacts:
  files:
    - web-api.0.0.1
    - appspec.yml
    - env
    - codedeploy/*
cache:
  paths:
    - "/go/pkg/**/*"
    - "/go/pkg/**.*"
