# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.bridges.artifacts.protos.vault_api_pb2 as vault__api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vault_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProviderCredential = channel.unary_unary(
                '/vault_api.VaultService/CreateProviderCredential',
                request_serializer=vault__api__pb2.CreateProviderCredentialRequest.SerializeToString,
                response_deserializer=vault__api__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.GetAllOrganizationCredential = channel.unary_unary(
                '/vault_api.VaultService/GetAllOrganizationCredential',
                request_serializer=vault__api__pb2.GetAllOrganizationCredentialRequest.SerializeToString,
                response_deserializer=vault__api__pb2.GetAllOrganizationCredentialResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/vault_api.VaultService/DeleteCredential',
                request_serializer=vault__api__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=vault__api__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.GetCredential = channel.unary_unary(
                '/vault_api.VaultService/GetCredential',
                request_serializer=vault__api__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=vault__api__pb2.GetCredentialResponse.FromString,
                _registered_method=True)
        self.GetOauth2Credential = channel.unary_unary(
                '/vault_api.VaultService/GetOauth2Credential',
                request_serializer=vault__api__pb2.GetCredentialRequest.SerializeToString,
                response_deserializer=vault__api__pb2.GetCredentialResponse.FromString,
                _registered_method=True)


class VaultServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProviderCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOrganizationCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOauth2Credential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProviderCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProviderCredential,
                    request_deserializer=vault__api__pb2.CreateProviderCredentialRequest.FromString,
                    response_serializer=vault__api__pb2.GetCredentialResponse.SerializeToString,
            ),
            'GetAllOrganizationCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOrganizationCredential,
                    request_deserializer=vault__api__pb2.GetAllOrganizationCredentialRequest.FromString,
                    response_serializer=vault__api__pb2.GetAllOrganizationCredentialResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=vault__api__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=vault__api__pb2.GetCredentialResponse.SerializeToString,
            ),
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=vault__api__pb2.GetCredentialRequest.FromString,
                    response_serializer=vault__api__pb2.GetCredentialResponse.SerializeToString,
            ),
            'GetOauth2Credential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOauth2Credential,
                    request_deserializer=vault__api__pb2.GetCredentialRequest.FromString,
                    response_serializer=vault__api__pb2.GetCredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vault_api.VaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vault_api.VaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProviderCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault_api.VaultService/CreateProviderCredential',
            vault__api__pb2.CreateProviderCredentialRequest.SerializeToString,
            vault__api__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllOrganizationCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault_api.VaultService/GetAllOrganizationCredential',
            vault__api__pb2.GetAllOrganizationCredentialRequest.SerializeToString,
            vault__api__pb2.GetAllOrganizationCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault_api.VaultService/DeleteCredential',
            vault__api__pb2.DeleteCredentialRequest.SerializeToString,
            vault__api__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault_api.VaultService/GetCredential',
            vault__api__pb2.GetCredentialRequest.SerializeToString,
            vault__api__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOauth2Credential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault_api.VaultService/GetOauth2Credential',
            vault__api__pb2.GetCredentialRequest.SerializeToString,
            vault__api__pb2.GetCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
