// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: lead-api.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeadGeneratorService_CreateLead_FullMethodName = "/lead_api.LeadGeneratorService/CreateLead"
)

// LeadGeneratorServiceClient is the client API for LeadGeneratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeadGeneratorServiceClient interface {
	CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*BaseResponse, error)
}

type leadGeneratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeadGeneratorServiceClient(cc grpc.ClientConnInterface) LeadGeneratorServiceClient {
	return &leadGeneratorServiceClient{cc}
}

func (c *leadGeneratorServiceClient) CreateLead(ctx context.Context, in *CreateLeadRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, LeadGeneratorService_CreateLead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeadGeneratorServiceServer is the server API for LeadGeneratorService service.
// All implementations should embed UnimplementedLeadGeneratorServiceServer
// for forward compatibility.
type LeadGeneratorServiceServer interface {
	CreateLead(context.Context, *CreateLeadRequest) (*BaseResponse, error)
}

// UnimplementedLeadGeneratorServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeadGeneratorServiceServer struct{}

func (UnimplementedLeadGeneratorServiceServer) CreateLead(context.Context, *CreateLeadRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLead not implemented")
}
func (UnimplementedLeadGeneratorServiceServer) testEmbeddedByValue() {}

// UnsafeLeadGeneratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeadGeneratorServiceServer will
// result in compilation errors.
type UnsafeLeadGeneratorServiceServer interface {
	mustEmbedUnimplementedLeadGeneratorServiceServer()
}

func RegisterLeadGeneratorServiceServer(s grpc.ServiceRegistrar, srv LeadGeneratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedLeadGeneratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeadGeneratorService_ServiceDesc, srv)
}

func _LeadGeneratorService_CreateLead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeadGeneratorServiceServer).CreateLead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeadGeneratorService_CreateLead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeadGeneratorServiceServer).CreateLead(ctx, req.(*CreateLeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LeadGeneratorService_ServiceDesc is the grpc.ServiceDesc for LeadGeneratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeadGeneratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lead_api.LeadGeneratorService",
	HandlerType: (*LeadGeneratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLead",
			Handler:    _LeadGeneratorService_CreateLead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lead-api.proto",
}
