// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: sendgrid-api.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WelcomeEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	To     *Contact `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *WelcomeEmailRequest) Reset() {
	*x = WelcomeEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeEmailRequest) ProtoMessage() {}

func (x *WelcomeEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeEmailRequest.ProtoReflect.Descriptor instead.
func (*WelcomeEmailRequest) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WelcomeEmailRequest) GetTo() *Contact {
	if x != nil {
		return x.To
	}
	return nil
}

type WelcomeEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *WelcomeEmailResponse) Reset() {
	*x = WelcomeEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WelcomeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeEmailResponse) ProtoMessage() {}

func (x *WelcomeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeEmailResponse.ProtoReflect.Descriptor instead.
func (*WelcomeEmailResponse) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{2}
}

func (x *WelcomeEmailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WelcomeEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResetPasswordEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	To                *Contact `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ResetPasswordLink string   `protobuf:"bytes,3,opt,name=resetPasswordLink,proto3" json:"resetPasswordLink,omitempty"`
}

func (x *ResetPasswordEmailRequest) Reset() {
	*x = ResetPasswordEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPasswordEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailRequest) ProtoMessage() {}

func (x *ResetPasswordEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailRequest) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{3}
}

func (x *ResetPasswordEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResetPasswordEmailRequest) GetTo() *Contact {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ResetPasswordEmailRequest) GetResetPasswordLink() string {
	if x != nil {
		return x.ResetPasswordLink
	}
	return ""
}

type ResetPasswordEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ResetPasswordEmailResponse) Reset() {
	*x = ResetPasswordEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetPasswordEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordEmailResponse) ProtoMessage() {}

func (x *ResetPasswordEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordEmailResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordEmailResponse) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPasswordEmailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResetPasswordEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InviteMemeberEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId           uint64   `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	To               *Contact `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	OrganizationName string   `protobuf:"bytes,3,opt,name=organizationName,proto3" json:"organizationName,omitempty"`
	ProjectName      string   `protobuf:"bytes,4,opt,name=projectName,proto3" json:"projectName,omitempty"`
	InviterName      string   `protobuf:"bytes,5,opt,name=inviterName,proto3" json:"inviterName,omitempty"`
}

func (x *InviteMemeberEmailRequest) Reset() {
	*x = InviteMemeberEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteMemeberEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemeberEmailRequest) ProtoMessage() {}

func (x *InviteMemeberEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemeberEmailRequest.ProtoReflect.Descriptor instead.
func (*InviteMemeberEmailRequest) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{5}
}

func (x *InviteMemeberEmailRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InviteMemeberEmailRequest) GetTo() *Contact {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *InviteMemeberEmailRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *InviteMemeberEmailRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *InviteMemeberEmailRequest) GetInviterName() string {
	if x != nil {
		return x.InviterName
	}
	return ""
}

type InviteMemeberEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Success bool  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *InviteMemeberEmailResponse) Reset() {
	*x = InviteMemeberEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendgrid_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteMemeberEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemeberEmailResponse) ProtoMessage() {}

func (x *InviteMemeberEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sendgrid_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemeberEmailResponse.ProtoReflect.Descriptor instead.
func (*InviteMemeberEmailResponse) Descriptor() ([]byte, []int) {
	return file_sendgrid_api_proto_rawDescGZIP(), []int{6}
}

func (x *InviteMemeberEmailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InviteMemeberEmailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sendgrid_api_proto protoreflect.FileDescriptor

var file_sendgrid_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x6e, 0x64, 0x67, 0x72, 0x69, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x22, 0x33, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x13, 0x57, 0x65,
	0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52,
	0x02, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x14, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x19, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x28, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x2c, 0x0a, 0x11, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x4a, 0x0a, 0x1a, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x19, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x65,
	0x6d, 0x65, 0x62, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x02, 0x74, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x1a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x65, 0x62, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0xcb, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x67, 0x72, 0x69, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x0c, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x24, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x57, 0x65, 0x6c, 0x63,
	0x6f, 0x6d, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x6d, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6c, 0x0a, 0x11, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x2a, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x6d,
	0x65, 0x62, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2b, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x65, 0x6d, 0x65, 0x62, 0x65, 0x72,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x0a,
	0x17, 0x61, 0x69, 0x2e, 0x72, 0x61, 0x70, 0x69, 0x64, 0x61, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x61,
	0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x61, 0x70, 0x69, 0x64, 0x61, 0x61, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sendgrid_api_proto_rawDescOnce sync.Once
	file_sendgrid_api_proto_rawDescData = file_sendgrid_api_proto_rawDesc
)

func file_sendgrid_api_proto_rawDescGZIP() []byte {
	file_sendgrid_api_proto_rawDescOnce.Do(func() {
		file_sendgrid_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendgrid_api_proto_rawDescData)
	})
	return file_sendgrid_api_proto_rawDescData
}

var file_sendgrid_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sendgrid_api_proto_goTypes = []any{
	(*Contact)(nil),                    // 0: integration_api.Contact
	(*WelcomeEmailRequest)(nil),        // 1: integration_api.WelcomeEmailRequest
	(*WelcomeEmailResponse)(nil),       // 2: integration_api.WelcomeEmailResponse
	(*ResetPasswordEmailRequest)(nil),  // 3: integration_api.ResetPasswordEmailRequest
	(*ResetPasswordEmailResponse)(nil), // 4: integration_api.ResetPasswordEmailResponse
	(*InviteMemeberEmailRequest)(nil),  // 5: integration_api.InviteMemeberEmailRequest
	(*InviteMemeberEmailResponse)(nil), // 6: integration_api.InviteMemeberEmailResponse
}
var file_sendgrid_api_proto_depIdxs = []int32{
	0, // 0: integration_api.WelcomeEmailRequest.to:type_name -> integration_api.Contact
	0, // 1: integration_api.ResetPasswordEmailRequest.to:type_name -> integration_api.Contact
	0, // 2: integration_api.InviteMemeberEmailRequest.to:type_name -> integration_api.Contact
	1, // 3: integration_api.SendgridService.WelcomeEmail:input_type -> integration_api.WelcomeEmailRequest
	3, // 4: integration_api.SendgridService.ResetPasswordEmail:input_type -> integration_api.ResetPasswordEmailRequest
	5, // 5: integration_api.SendgridService.InviteMemberEmail:input_type -> integration_api.InviteMemeberEmailRequest
	2, // 6: integration_api.SendgridService.WelcomeEmail:output_type -> integration_api.WelcomeEmailResponse
	4, // 7: integration_api.SendgridService.ResetPasswordEmail:output_type -> integration_api.ResetPasswordEmailResponse
	6, // 8: integration_api.SendgridService.InviteMemberEmail:output_type -> integration_api.InviteMemeberEmailResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sendgrid_api_proto_init() }
func file_sendgrid_api_proto_init() {
	if File_sendgrid_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendgrid_api_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WelcomeEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ResetPasswordEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ResetPasswordEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*InviteMemeberEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendgrid_api_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*InviteMemeberEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendgrid_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sendgrid_api_proto_goTypes,
		DependencyIndexes: file_sendgrid_api_proto_depIdxs,
		MessageInfos:      file_sendgrid_api_proto_msgTypes,
	}.Build()
	File_sendgrid_api_proto = out.File
	file_sendgrid_api_proto_rawDesc = nil
	file_sendgrid_api_proto_goTypes = nil
	file_sendgrid_api_proto_depIdxs = nil
}
