name: Bug
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug ðŸ™  
        Clear bug reports help keep Rapida reliable in production.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What happened?
      placeholder: Audio streaming stops after 30s when concurrent calls > 50
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Streaming should continue without interruption.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Start Rapida with config X
        2. Initiate 50 concurrent calls
        3. Observe streaming behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Rapida version
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or traces (optional)
      description: Paste relevant logs, traces, or metrics.
      render: shell

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment type
      options:
        - SaaS
        - Local / Dev
        - Docker
        - Kubernetes
        - Managed / Cloud
