name: Feature
description: Suggest a new feature or improvement
title: "[Feature]: "
labels:
  - feature
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make Rapida better?  
        We’d love to hear how it helps real production voice systems.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: Difficult to route calls between multiple agents dynamically.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
      placeholder: Add agent handoff via tool calls with shared state.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternatives you’ve tried?
    validations:
      required: false

  - type: dropdown
    id: impact
    attributes:
      label: Impact area
      options:
        - Orchestration
        - Voice / Audio
        - LLM / Agent logic
        - Observability
        - SDK
        - Deployment
