export const EndpointTag = [
  'agent simulations',
  'agents',
  'autonomous agents',
  'chatbots',
  'classification',
  'code understanding',
  'code writing',
  'evaluation',
  'extraction',
  'interacting with apis',
  'multi-modal',
  'qa-over-documents',
  'self-checking',
  'sql',
  'summarization',
  'tagging',
  'classification',
  'evaluation',
];
