export const KnowledgeTags = [
  'healthcare',
  'finance',
  'retail',
  'manufacturing',
  'education',
  'technology',
  'energy',
  'transportation',
  'hospitality',
  'construction',
  'invoice',
  'contract',
  'report',
  'purchase order',
  'proposal',
  'manual',
  'policy document',
  'certification',
  'blueprint',
  'research paper',
  'user guide',
  'service agreement',
  'employment agreement',
  'non-disclosure agreement',
  'memorandum',
  'meeting minutes',
  'white paper',
  'case study',
  'financial statement',
  'business plan',
  'tax return',
  'audit report',
  'insurance policy',
  'legal brief',
  'technical specification',
  'product brochure',
  'bill of lading',
  'shipping manifest',
  'customer feedback form',
  'survey results',
  'risk assessment',
  'project plan',
  'progress report',
  'sales order',
  'work order',
  'tender document',
  'marketing plan',
  'press release',
  'expense report',
  'warranty document',
  'safety data sheet',
  'compliance report',
  'evaluation form',
  'training material',
  'standard operating procedure (sop)',
  'feasibility study',
  'affidavit',
  'loan agreement',
  'patent application',
  'annual report',
  'faqs',
  'knowledge base articles',
  'troubleshooting guides',
  'product manuals',
  'setup and installation guides',
  'tutorial videos',
  'user onboarding material',
  'service level agreement (sla)',
  'return and refund policy',
  'customer support scripts',
  'chatbot responses',
  'email templates',
  'ticket escalation procedures',
  'common issue resolutions',
  'billing and payment instructions',
  'service outage notifications',
  'live chat guidance',
  'account management guides',
  'feature update announcements',
  'community forum guidelines',
  'terms and conditions',
  'privacy policy',
  'warranty information',
  'replacement and repair policy',
  'product comparisons',
  'upgrade instructions',
  'subscription management guide',
  'user permissions and roles documentation',
  'security guidelines',
  'data backup instructions',
  'multi-language support content',
  'contact information',
  'support team escalation matrix',
  'incident response plan',
  'service downtime faq',
  'service restoration procedures',
  'feedback collection forms',
  'customer satisfaction survey templates',
  'live chat protocols',
  'social media response templates',
  'holiday and off-hour support schedule',
  'remote support guidelines',
  'feature usage tips',
  'voice support call scripts',
  'service subscription renewal process',
  'incident reporting form',
  'self-service portal user guide',
  'account termination process',
  'product return procedure',
  'knowledge base index',
];
