import { SetMetadata } from '@/utils/metadata';
import { Metadata } from '@rapidaai/react';

export const PLAYHT_LANGUAGE = [
  { code: 'af', name: 'Afrikaans' },
  { code: 'am', name: 'Amharic' },
  { code: 'ar', name: 'Arabic' },
  { code: 'as', name: 'Assamese' },
  { code: 'az', name: 'Azerbaijani' },
  { code: 'bg', name: 'Bulgarian' },
  { code: 'bn', name: 'Bangla' },
  { code: 'bs', name: 'Bosnian' },
  { code: 'ca', name: 'Catalan' },
  { code: 'cs', name: 'Czech' },
  { code: 'cy', name: 'Welsh' },
  { code: 'da', name: 'Danish' },
  { code: 'de', name: 'German' },
  { code: 'el', name: 'Greek' },
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Spanish' },
  { code: 'et', name: 'Estonian' },
  { code: 'eu', name: 'Basque' },
  { code: 'fa', name: 'Persian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'fil', name: 'Filipino' },
  { code: 'fr', name: 'French' },
  { code: 'ga', name: 'Irish' },
  { code: 'gl', name: 'Galician' },
  { code: 'gu', name: 'Gujarati' },
  { code: 'he', name: 'Hebrew' },
  { code: 'hi', name: 'Hindi' },
  { code: 'hr', name: 'Croatian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'hy', name: 'Armenian' },
  { code: 'id', name: 'Indonesian' },
  { code: 'is', name: 'Icelandic' },
  { code: 'it', name: 'Italian' },
  { code: 'ja', name: 'Japanese' },
  { code: 'jv', name: 'Javanese' },
  { code: 'ka', name: 'Georgian' },
  { code: 'kk', name: 'Kazakh' },
  { code: 'km', name: 'Khmer' },
  { code: 'kn', name: 'Kannada' },
  { code: 'ko', name: 'Korean' },
  { code: 'lo', name: 'Lao' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'mk', name: 'Macedonian' },
  { code: 'ml', name: 'Malayalam' },
  { code: 'mn', name: 'Mongolian' },
  { code: 'mr', name: 'Marathi' },
  { code: 'ms', name: 'Malay' },
  { code: 'mt', name: 'Maltese' },
  { code: 'my', name: 'Burmese' },
  { code: 'nb', name: 'Norwegian Bokmål' },
  { code: 'ne', name: 'Nepali' },
  { code: 'nl', name: 'Dutch' },
  { code: 'or', name: 'Odia' },
  { code: 'pa', name: 'Punjabi' },
  { code: 'pl', name: 'Polish' },
  { code: 'ps', name: 'Pashto' },
  { code: 'pt', name: 'Portuguese' },
  { code: 'ro', name: 'Romanian' },
  { code: 'ru', name: 'Russian' },
  { code: 'si', name: 'Sinhala' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' },
  { code: 'so', name: 'Somali' },
  { code: 'sq', name: 'Albanian' },
  { code: 'sr', name: 'Serbian' },
  { code: 'su', name: 'Sundanese' },
  { code: 'sv', name: 'Swedish' },
  { code: 'sw', name: 'Swahili' },
  { code: 'ta', name: 'Tamil' },
  { code: 'te', name: 'Telugu' },
  { code: 'th', name: 'Thai' },
  { code: 'tr', name: 'Turkish' },
  { code: 'uk', name: 'Ukrainian' },
  { code: 'ur', name: 'Urdu' },
  { code: 'uz', name: 'Uzbek' },
  { code: 'vi', name: 'Vietnamese' },
  { code: 'zh', name: 'Chinese' },
  { code: 'zu', name: 'Zulu' },
];

export const PLAYHT_VOICES = [
  {
    id: 's3://voice-cloning-zero-shot/d82d246c-148b-457f-9668-37b789520891/adolfosaad/manifest.json',
    name: 'Adolfo',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/adolfo.wav',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/a59cb96d-bba8-4e24-81f2-e60b888a0275/charlottenarrativesaad/manifest.json',
    name: 'Charlotte (Narrative)',
    sample:
      'https://parrot-samples.s3.amazonaws.com/kettle/charlotte+(narrative).wav',
    accent: 'canadian',
    age: 'adult',
    gender: 'female',
    language: 'English (CA)',
    language_code: 'en-CA',
    loudness: 'low',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/3a831d1f-2183-49de-b6d8-33f16b2e9867/dylansaad/manifest.json',
    name: 'Dylan',
    sample: 'https://peregrine-results.s3.amazonaws.com/AAc418f41vBRkHNOdi.mp3',
    accent: 'british',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'gaming',
    tempo: 'slow',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/f6594c50-e59b-492c-bac2-047d57f8bdd8/susanadvertisingsaad/manifest.json',
    name: 'Susan (Advertising)',
    sample:
      'https://parrot-samples.s3.amazonaws.com/kettle/susan+(advertising).wav',
    accent: 'american',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/e5df2eb3-5153-40fa-9f6e-6e27bbb7a38e/original/manifest.json',
    name: 'Navya',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Navya.wav',
    accent: 'indian',
    gender: 'female',
    language: 'English (IN)',
    language_code: 'en-IN',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/b41d1a8c-2c99-4403-8262-5808bc67c3e0/bentonsaad/manifest.json',
    name: 'Benton',
    sample: 'https://peregrine-results.s3.amazonaws.com/fPBgu4E0dT9eMkxIe0.mp3',
    accent: 'american',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'videos',
    tempo: 'fast',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/9fc626dc-f6df-4f47-a112-39461e8066aa/oliviaadvertisingsaad/manifest.json',
    name: 'Olivia (Advertising)',
    sample:
      'https://parrot-samples.s3.amazonaws.com/kettle/olivia+advertising.wav',
    accent: 'canadian',
    gender: 'female',
    language: 'English (CA)',
    language_code: 'en-CA',
    style: 'advertising',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/1afba232-fae0-4b69-9675-7f1aac69349f/delilahsaad/manifest.json',
    name: 'Delilah',
    sample: 'https://peregrine-results.s3.amazonaws.com/UlI3kAAfgCOJNP2OMe.mp3',
    accent: 'american',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/9f1ee23a-9108-4538-90be-8e62efc195b6/charlessaad/manifest.json',
    name: 'Charles',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/charles.wav',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/473c81b1-93ea-4662-9e63-7d65392e5f9b/madisonsaad/manifest.json',
    name: 'Madison',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/madison.wav',
    accent: 'irish',
    age: 'old',
    gender: 'female',
    language: 'English (IE)',
    language_code: 'en-IE',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'slow',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/2879ab87-3775-4992-a228-7e4f551658c2/fredericksaad2/manifest.json',
    name: 'Frederick',
    sample: 'https://peregrine-results.s3.amazonaws.com/rixIUBC2k3d0xHY4B2.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'male',
    language: 'English (GB)',
    language_code: 'en-GB',
    loudness: 'low',
    style: 'narrative',
    tempo: 'slow',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/a540a448-a9ca-446c-9538-d1bae6c506f1/original/manifest.json',
    name: 'Mason',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Mason.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/a5cc7dd9-069c-4fe8-9ae7-0c4bae4779c5/micahsaad/manifest.json',
    name: 'Micah',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/micah.wav',
    accent: 'british',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/d99d35e6-e625-4fa4-925a-d65172d358e1/adriansaad/manifest.json',
    name: 'Adrian',
    sample: 'https://peregrine-results.s3.amazonaws.com/0hjUhtQD61YXtW39OP.mp3',
    accent: 'american',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/97580643-b568-4198-aaa4-3e07e4a06c47/original/manifest.json',
    name: 'Indigo',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Indigo.wav',
    accent: 'british',
    gender: 'female',
    language: 'English (GB)',
    language_code: 'en-GB',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/36e9c53d-ca4e-4815-b5ed-9732be3839b4/samuelsaad/manifest.json',
    name: 'Samuel',
    sample: 'https://peregrine-results.s3.amazonaws.com/ww8lf6xg9KAGV6kfyg.mp3',
    accent: 'american',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'narrative',
    tempo: 'slow',
    texture: 'gravelly',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/743575eb-efdc-4c10-b185-a5018148822f/original/manifest.json',
    name: 'Calvin',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Calvin.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/7b97b543-7877-41b6-86ee-aa1e0b6c110e/dicksaad/manifest.json',
    name: 'Dick',
    sample: 'https://peregrine-results.s3.amazonaws.com/ydgska4ZaIJ3bmRy0t.mp3',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'training',
    tempo: 'fast',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/34eaa933-62cb-4e32-adb8-c1723ef85097/original/manifest.json',
    name: 'Amelia',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Amelia.wav',
    accent: 'british',
    gender: 'female',
    language: 'English (GB)',
    language_code: 'en-GB',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/cebaa3cf-d1d5-4625-ba20-03dcca3b379f/sargesaad/manifest.json',
    name: 'Sarge',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/sarge.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    style: 'gaming',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/688d0200-7415-42b4-8726-e2f5693aaac8/williamnarrativesaad/manifest.json',
    name: 'William (Narrative)',
    sample: 'https://peregrine-results.s3.amazonaws.com/BRbOe9n93ab1YI2Hot.mp3',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/9a5deeda-3025-49c5-831a-ac98f86f2a37/aprilsaad/manifest.json',
    name: 'April',
    sample: 'https://peregrine-results.s3.amazonaws.com/nbrn3tdfuXIxGn8TIl.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/def0cd31-1b8c-486e-82d2-050a0ea2965d/axelsaad/manifest.json',
    name: 'Axel',
    sample: 'https://peregrine-results.s3.amazonaws.com/N5TqVLG8y2deM1e5bQ.mp3',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'fast',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/d712cad5-85db-44c6-8ee0-8f4361ed537b/eleanorsaad2/manifest.json',
    name: 'Eleanor',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/eleanor-2.wav',
    accent: 'british',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/9b559f3c-22e7-4b10-8158-3e11b333751e/dudleysaad/manifest.json',
    name: 'Dudley',
    sample: 'https://peregrine-results.s3.amazonaws.com/TzWYqWMTlbSF11bYhd.mp3',
    accent: 'american',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'low',
    style: 'narrative',
    tempo: 'fast',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/0c4c229f-7f99-4ed9-b904-223c701672b9/phoebesaad/manifest.json',
    name: 'Phoebe',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/Phoebe.wav',
    accent: 'british',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'videos',
    tempo: 'fast',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/ff414883-0e32-4a92-a688-d7875922120d/original/manifest.json',
    name: 'Autumn',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Autumn.wav',
    accent: 'american',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/a0fa25cc-5f42-4dd0-8a78-a950dd5297cd/original/manifest.json',
    name: 'Isabella',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Isabella.wav',
    accent: 'british',
    gender: 'female',
    language: 'English (GB)',
    language_code: 'en-GB',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/509221d8-9e2d-486c-9b3c-97e52d86e63d/arthuradvertisingsaad/manifest.json',
    name: 'Arthur (Advertising)',
    sample: 'https://peregrine-results.s3.amazonaws.com/z05Mb3TymF75TcQnyV.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'male',
    language: 'English (GB)',
    language_code: 'en-GB',
    loudness: 'neutral',
    style: 'advertising',
    tempo: 'neutral',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/37e5af8b-800a-4a76-8f31-4203315f8a9e/billysaad/manifest.json',
    name: 'Billy',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/billy.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    style: 'gaming',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/7447d346-20d5-4939-b43c-bdf17e757e98/cliftonsaad/manifest.json',
    name: 'Clifton',
    sample: 'https://peregrine-results.s3.amazonaws.com/IQqwyNGPmk3cF7x5QG.mp3',
    accent: 'american',
    age: 'old',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'gravelly',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/2a7ddfc5-d16a-423a-9441-5b13290998b8/novasaad/manifest.json',
    name: 'Nova',
    sample: 'https://peregrine-results.s3.amazonaws.com/H2u1NBpnzUYJD0pgDF.mp3',
    accent: 'american',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'whisper',
    style: 'narrative',
    tempo: 'slow',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/dc90b58b-59a9-4e65-955d-c7620deb2d7a/original/manifest.json',
    name: 'Richie',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Richie.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/7142f297-c55f-451d-8863-108d5101b5ed/susantrainingsaad/manifest.json',
    name: 'Susan (Training)',
    sample:
      'https://parrot-samples.s3.amazonaws.com/kettle/susan+(training).wav',
    accent: 'american',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'high',
    style: 'training',
    tempo: 'neutral',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/fd35d956-b644-4513-9cd0-7aa6931dfd43/juliansaad/manifest.json',
    name: 'Julian',
    sample: 'https://peregrine-results.s3.amazonaws.com/nHg2pd7S5L9ctKScRX.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'male',
    language: 'English (GB)',
    language_code: 'en-GB',
    loudness: 'neutral',
    style: 'videos',
    tempo: 'neutral',
    texture: 'round',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/bb759cd0-edb0-43d9-8273-f0a7c048fb11/original/manifest.json',
    name: 'Lachlan',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Lachlan.wav',
    accent: 'australian',
    gender: 'male',
    language: 'English (AU)',
    language_code: 'en-AU',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/e46b4027-b38d-4d24-b292-38fbca2be0ef/original/manifest.json',
    name: 'Atlas',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Atlas.wav',
    accent: 'american',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/aa753d26-bc20-479f-95af-5c3c1c970d93/original/manifest.json',
    name: 'Finley',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Finley.wav',
    accent: 'british',
    gender: 'male',
    language: 'English (GB)',
    language_code: 'en-GB',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/74f59ea4-f07b-4d10-88d1-ca174adac3f3/original/manifest.json',
    name: 'Pia',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Pia.wav',
    accent: 'australian',
    gender: 'female',
    language: 'English (AU)',
    language_code: 'en-AU',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/80ba8839-a6e6-470c-8f68-7c1e5d3ee2ff/abigailsaad/manifest.json',
    name: 'Abigail',
    sample: 'https://peregrine-results.s3.amazonaws.com/hbGWSpDCmbkVnEGmAl.mp3',
    accent: 'american',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    style: 'narrative',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/a72a5d4c-d729-4045-8bc8-1786043a4537/cartersaad/manifest.json',
    name: 'Carter',
    sample: 'https://parrot-samples.s3.amazonaws.com/kettle/carter.wav',
    accent: 'american',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/f8af54e1-1534-4f68-ad8a-260cc132f820/original/manifest.json',
    name: 'Nigel',
    sample: 'https://parrot-samples.s3.amazonaws.com/gargamel/Nigel.wav',
    accent: 'australian',
    gender: 'male',
    language: 'English (AU)',
    language_code: 'en-AU',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/8ca8c44d-fb2b-4269-abca-4e6748a4a61e/arthursaad/manifest.json',
    name: 'Arthur',
    sample: 'https://peregrine-results.s3.amazonaws.com/B7H8TzHvhzdEd9XG3y.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'male',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'narrative',
    tempo: 'neutral',
    texture: 'smooth',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
  {
    id: 's3://voice-cloning-zero-shot/0a11e4f0-1656-48c9-bc4c-affcd718c414/madelynsaad/manifest.json',
    name: 'Madelyn',
    sample: 'https://peregrine-results.s3.amazonaws.com/hFF3qzi7zRuub0K9T7.mp3',
    accent: 'british',
    age: 'adult',
    gender: 'female',
    language: 'English (US)',
    language_code: 'en-US',
    loudness: 'neutral',
    style: 'videos',
    tempo: 'fast',
    texture: 'thick',
    is_cloned: false,
    voice_engine: 'PlayHT2.0',
  },
];
export const PLAYHT_MODELS = [
  { name: 'Play 2.0', id: 'play-2.0' },
  { name: 'Play 3.0 Mini', id: 'play-3.0-mini' },
  { name: 'PlayDialog', id: 'playdialog' },
];

export const GetPlayHTDefaultOptions = (current: Metadata[]): Metadata[] => {
  const mtds: Metadata[] = [];

  // Define the keys we want to keep
  const keysToKeep = [
    'rapida.credential_id',
    'speak.language',
    'speak.voice.id',
    'speak.model',
  ];

  // Function to create or update metadata
  const addMetadata = (
    key: string,
    defaultValue?: string,
    validationFn?: (value: string) => boolean,
  ) => {
    const metadata = SetMetadata(current, key, defaultValue, validationFn);
    if (metadata) mtds.push(metadata);
  };

  addMetadata('rapida.credential_id');

  // Set language
  addMetadata('speak.language', 'en', value =>
    PLAYHT_LANGUAGE.some(l => l.code === value),
  );

  // Set voice
  addMetadata(
    'speak.voice.id',
    's3://voice-cloning-zero-shot/d82d246c-148b-457f-9668-37b789520891/adolfosaad/manifest.json',
    value => PLAYHT_VOICES.some(v => v.id === value),
  );

  // Set model
  addMetadata('speak.model', 'play-2.0', value =>
    PLAYHT_MODELS.some(m => m.id === value),
  );

  // Only return metadata for the keys we want to keep
  return [
    ...mtds.filter(m => keysToKeep.includes(m.getKey())),
    ...current.filter(m => m.getKey().startsWith('speaker.')),
  ];
};

export const ValidatePlayHTOptions = (options: Metadata[]): boolean => {
  const credentialID = options.find(
    opt => opt.getKey() === 'rapida.credential_id',
  );
  if (
    !credentialID ||
    !credentialID.getValue() ||
    credentialID.getValue().length === 0
  ) {
    return false;
  }

  // Validate language
  const languageOption = options.find(opt => opt.getKey() === 'speak.language');
  if (
    !languageOption ||
    !PLAYHT_LANGUAGE.some(lang => lang.code === languageOption.getValue())
  ) {
    return false;
  }

  // Validate voice
  const voiceOption = options.find(opt => opt.getKey() === 'speak.voice.id');
  if (
    !voiceOption ||
    !PLAYHT_VOICES.some(voice => voice.id === voiceOption.getValue())
  ) {
    return false;
  }

  // Validate model
  const modelOption = options.find(opt => opt.getKey() === 'speak.model');
  if (
    !modelOption ||
    !PLAYHT_MODELS.some(model => model.id === modelOption.getValue())
  ) {
    return false;
  }

  return true;
};
