version: 0.0

os: linux

files:
  - source: requirements.txt
    destination: /opt/app/backend-app/artifacts/document-api/
    overwrite: true
  - source: config.yaml
    destination: /opt/app/backend-app/artifacts/document-api/
    overwrite: true
  - source: document-api/build/  # Assuming your output is now in OUT_DIR
    destination: /opt/app/backend-app/artifacts/document-api/app/
    overwrite: true

hooks:
  BeforeInstall:
    - location: codedeploy/BeforeInstall.sh
      timeout: 180
      runas: deploy-agent
      
  ApplicationStop:
    - location: codedeploy/ApplicationStop.sh
      timeout: 180
      runas: deploy-agent

  AfterInstall:
    - location: codedeploy/AfterInstall.sh
      timeout: 1000
      runas: deploy-agent

  ApplicationStart:
    - location: codedeploy/ApplicationStart.sh
      timeout: 180
      runas: deploy-agent

  ValidateService:
    - location: codedeploy/ValidateService.sh
      timeout: 180
      runas: deploy-agent